config/routes.rb
InternalProjMgmt::Application.routes.draw do
  get 'register' => 'users#new'
  get '/search/:keyword' => 'issues#search'
  get 'rebuild_index' => 'issues#rebuild_index'
  get '/stats' => "pages#stats"

  post '/user_sessions' => "user_sessions#create"
  get 'logout' => "user_sessions#destroy"

  post '/assigned_issues/sort' => 'issue_assignments#sort'
  
  resources :activities, :only => :create
  resources :users, :comments
  resources :projects do
    resources :issues do
      collection do
        get 'new/:label' => 'issues#new'
        get 'filter/:state', :action => 'index'
        get 'label/:label', :action => 'view_by_label'
      end
    end
    resources :milestones, :documents
  end

  get "milestones/new"
  post "milestones/create"

  resources :issues do
    resources :comments
    resources :todo_items

    member do
      post 'change_state'
      post 'assign_to'
      post 'planning'
    end

    collection do
      get 'autocomplete'
    end
  end

  resources :todo_items do
    member do
      post :change_state
    end

    collection do
      post :sort
    end
  end

  resource :account
  resources :images, :only => [:new, :create, :destroy]

  namespace 'sudo' do
    resources :users
  end

  root :to => "pages#index"

end

app/models/issue.rb
# == Schema Information
# Schema version: 20110605071315
#
# Table name: issues
#
#  id             :integer         not null, primary key
#  project_id     :integer
#  title          :string(255)
#  content        :text
#  workflow_state :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#  user_id        :integer
#  label          :string(255)
#  milestone_id   :integer
#  planned_date   :date
#

class Issue < ActiveRecord::Base
  include Workflow

  workflow do
    state :open do
      event :work_on, :transitions_to => :working_on
      event :close, :transitions_to => :closed
    end

    state :working_on do
      event :pause, :transitions_to => :paused
      event :mark_finished, :transitions_to => :finished
    end

    state :paused do
      event :continue, :transitions_to => :working_on
      event :close, :transitions_to => :closed
    end

    state :finished do
      event :continue, :transitions_to => :working_on
      event :close, :transitions_to => :closed
    end

    state :closed do
      event :reopen, :transitions_to => :reopened
    end

    state :reopened do
      event :work_on, :transitions_to => :working_on
    end
  end

  belongs_to :project
  belongs_to :user
  belongs_to :milestone

  has_many :comments, :dependent => :destroy
  has_many :todo_items, :dependent => :destroy

  has_one :issue_assignment, :dependent => :destroy
  has_one :assigned_user, :through => :issue_assignment, :source => :user

  before_validation :set_default_content

  attr_protected :label

  validates :title, :content, :presence => true
  validates :user_id, :project_id, :presence => true
  validates :label, :presence => true, :on => :create

  def self.all_states
    [:open, :working_on, :paused, :finished, :closed, :reopened]
  end

  def self.state_name(state_sym)
    I18n.t("issue.state.#{state_sym.to_s}")
  end

  def self.event_name(event_sym)
    I18n.t("issue.event.#{event_sym.to_s}")
  end

  def self.valid_state?(state_sym)
    self.workflow_spec.states.keys.member? state_sym
  end

  def current_state_name
    Issue.state_name(self.current_state.name)
  end

  def default_content
    I18n.t('issue.default_content')
  end

  class << self
    Issue.workflow_spec.states.keys.each do |state_sym|
      define_method("only_#{state_sym.to_s}") do
        where(:workflow_state => state_sym)
      end

      define_method("except_#{state_sym.to_s}") do
        where(["workflow_state != ?", state_sym.to_s])
      end
    end
  end

  def to_index_hash
    {:id => self.id, :title => self.title, :content => self.content}
  end

  private
    def set_default_content
      self.content = default_content if self.content.blank?
    end

    def self.get_index
      index_dir = Issue.get_index_dir
      FileUtils.mkdir_p(index_dir) unless File.exists?(index_dir)

      analyzer = RMMSeg::Ferret::Analyzer.new { |tok| Ferret::Analysis::LowerCaseFilter.new(tok) }
      Ferret::Index::Index.new(:path => index_dir, :analyzer => analyzer, :key => :id)
    end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_filter :must_login_first
  before_filter :find_issue, :only => [:show, :edit, :update, :destroy, :change_state, :assign_to]
  before_filter :only => [:edit, :update, :destroy] do |c|
    authorize! :manage, @issue
  end

  def index
    @project = Project.find(params[:project_id])
    if params[:state]
      @issue_state = Issue.valid_state?(params[:state].to_sym) ? params[:state] : :all
    else
      @issue_state = :all
    end

    @title = @project.name
    breadcrumbs.add @project.name, project_path(@project)
    breadcrumbs.add 'Issues', project_issues_path(@project)

    if @issue_state == :all
      @issues = @project.issues.except_closed
    else
      @issues = @project.issues.send("only_#{@issue_state}")
    end
  end

  def show
    breadcrumbs.add @issue.project.name, project_path(@issue.project)
    breadcrumbs.add '#' + "#{@issue.label}-#{@issue.id}", issue_path(@issue)

    @comment = @issue.comments.new
    @todo_item = @issue.todo_items.new
    @title = @issue.title
  end

  def view_by_label
    @label = params[:label]
    @project = Project.find(params[:project_id])
    @issues = @project.issues.where(['label = ?', @label])
    @title = @project.name
    breadcrumbs.add t(:all_projects), projects_path
    breadcrumbs.add @project.name, project_path(@project)
    
    render :index
  end

  def new
    @project = Project.find(params[:project_id])
    @issue = @project.issues.new
    @title = t('issue.create')
    @label = params[:label]
    
    breadcrumbs.add @issue.project.name, project_path(@issue.project)
    breadcrumbs.add t("new_#{@label}")
  end

  def create
    @project = Project.find(params[:project_id])
    @issue = @project.issues.new(params[:issue])
    @issue.label = params[:issue][:label]
    @issue.user = current_user 
    if @issue.save
      Activity.create!(
        :user_id => current_user.id,
        :project_id => params[:project_id],
        :event_name => 'create_issue',
        :target_id => @issue.id,
        :data => { :title => @issue.title, :project_name => @project.name, :label => @issue.label }
      )
      redirect_to @issue
    else
      render :new
    end
  end

  def edit
    @project = @issue.project
    @title = t('issue.edit')
    
    breadcrumbs.add @issue.project.name, project_path(@issue.project)
    breadcrumbs.add '#' + "#{@issue.label}-#{@issue.id}", issue_path(@issue)
    breadcrumbs.add t(:edit)
  end

  def update
    respond_to do |format|
      if @issue.update_attributes(params[:issue])
        format.html { redirect_to @issue }
        format.js { render :nothing => true }
      else
        format.html { redirect_to root_path }
        format.js { render :text => "SAVE_FAILED", :status => 500 }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @issue.destroy
        format.html { redirect_to @issue.project }
        format.js { render :nothing => true }
      else
        format.html { redirect_to root_path }
        format.js { render :text => "DESTROY_FAILED", :status => 500 }
      end
    end
  end

  def change_state
    authorize! :change_state, @issue
    respond_to do |format|
      if @issue.current_state.events.keys.member? params[:event].to_sym
        begin
          event_action = "#{params[:event]}!"
          @issue.send(event_action)
          Activity.create!(
            :user_id => current_user.id,
            :project_id => @issue.project.id,
            :event_name => 'change_issue_state',
            :target_id => @issue.id,
            :data => {:current_state => @issue.current_state.name, :issue_title => @issue.title}
          )
          format.html { redirect_to [@issue.project, @issue] }
          format.js { render :layout => false }
        rescue
          format.html { redirect_to root_path }
          format.js { render :text => "ERROR", :status => 500 }
        end
      else
        format.html { redirect_to root_path }
        format.js { render :text => "ERROR", :status => 500 }
      end
    end
  end

  def assign_to
    authorize! :assign, @issue
    user = User.find(params[:user_id])
    @issue.assigned_user = user
    Activity.create!(
      :user_id => current_user.id,
      :project_id => @issue.project.id,
      :event_name => 'assign_issue',
      :target_id => @issue.id,
      :data => {
        :issue_title => @issue.title,
        :assigned_id => params[:user_id],
        :assigned_name => user.name
      }
    )

    respond_to do |format|
        format.html { redirect_to @issue }
        format.js
    end
  end
  
  def planning
    @issue = Issue.find(params[:id])
    @new_date = params[:date].blank? ? '' : Date.parse(params[:date])
      
    if @issue.update_attributes(:planned_date => @new_date)
      render :json => {:success => true}
    else
      render :json => {:success => false}
    end
      
  end

  def search
    @result = []
  end

  def rebuild_index
    respond_to do |format|
      format.html {
        redirect_to root_path and return unless current_user.root?

        Issue.rebuild_index!
        redirect_to root_path
      }

      format.js {
        render :text => "ERROR", :status => 403 and return unless current_user.root?

        Issue.rebuild_index!
        head :ok
      }

    end

  end

  def autocomplete
    respond_to do |format|
      format.js { 
        result = []
        render :json => result and return if params[:term].nil? or params[:term].index('#') or params[:term] =~ /^issue/

        Issue.search_with_ferret(%(title:'#{params[:term]}')) do |index, id, score|
          issue = Issue.find(index[id][:id])
          result << {:label => issue.title, :value => "issue-#{issue.id}"}
        end
        render :json => result
      }
    end
  end

  private
    def find_issue
      @issue = Issue.find(params[:id])
    end

end

app/views/issues/_form.html.erb
<% content_for :head_hook do %>
  <%= javascript_include_tag 'uploadify.swfobject.js' %>
  <%= javascript_include_tag 'uploadify.214.js' %>
<% end %>

<% content_for :on_ready_hook do %>
  <% session_key_name = Rails.application.config.session_options[:key] %>
  $('#image_upload').uploadify({
    uploader: '/uploadify.swf',
    script: '<%= images_path %>',
    cancelImg: '/images/cancel_upload.png',
    fileDataName: 'image[file]',
    fileExt: '*.png,*.jpeg, *.jpg, *.gif',
    sizeLimit: <%= 10.megabytes %>,
    width: 150,
    height: 25,
    onComplete: function(a, b, c, response) {
      eval(response);
    },
    scriptData: {
      '_http_accept': 'application/javascript',
      '_method': 'POST',
      '<%= session_key_name %>': encodeURIComponent('<%= u cookies[session_key_name] %>'),
      'authenticity_token': encodeURIComponent('<%= u form_authenticity_token %>')
    },
    auto: true
  });

  $("#uploaded_images img").live('click', function() {
    var image_url = $(this).attr('src');
    $.GollumEditor.replaceSelection("![](" + image_url + ")");
  });

<% end %>

<%= form_for [@project, @issue] do |f| %>
  <div class="module_content">
    <%= render 'shared/error_messages', :obj => @issue %>
    <fieldset>
      <%= f.label :title, t(:title) %>
      <%= f.text_field :title %>
    </fieldset>

    <fieldset>
      <%= f.label :content, t(:content) %>
      <%= render :partial => 'shared/editor', :locals => {:name => 'issue[content]', :content => @issue.content} %>
    </fieldset>

    <%= file_field_tag :image_upload, :name => 'image[file]' %>
    <div id="uploaded_images"></div>

    <fieldset>
      <%= f.label :milestone, t(:milestone) %>
      <%= f.select :milestone_id, options_for_select(
        @project.milestones.collect { |m| [m.name, m.id] }.unshift([t(:empty_option), 0]),
        @issue.milestone ? @issue.milestone.id : 0
      ) %>
    </fieldset>

    <%= f.hidden_field :label, :value => @label %>
  </div>
  <footer>
    <div class="submit_link">
      <%= f.submit t(:save), :class => :alt_btn %>
    </div>
  </footer>
<% end %>

app/views/issues/_issue.html.erb
<div class="issue_item ui-corner-all">
  <span class="tiptip" title="<%= Issue.state_name(issue.current_state.name) %>">
    <%= image_tag "state_#{issue.current_state.name.to_s}.png", :align => :absmiddle, :height => 16, :width => 16 %>
  </span>
  <%= issue_title_link(issue) %>
  <span class="date"><%= time_ago_in_words(issue.created_at) + t(:ago) %></span>
</div>

app/views/issues/_manage_todo_list.html.erb
<h4><%= t(:todo) %></h4>

<%= render issue.todo_items.where(:workflow_state => :open), :manage => true %>

<div class="<%= "hide" if issue.closed? %>" id="add_todo_form">
	<%= form_for [issue, todo_item], :remote => true do |f| %>
	<fieldset>
		<%= f.text_area :content, :class => :micro %><br />
	</fieldset>
	<%= f.submit t(:add) %>
  <% end %>
</div>
    
<%= render issue.todo_items.where(:workflow_state => :done), :manage => true %>

app/views/issues/_simple_style.html.erb
<ul>
	<li><%= issue_title_link(issue) %></li>
</ul>

app/views/issues/_view_todo_list.html.erb
<% if issue.todo_items.any? %>
<div id="todo_list_box">
  <div class="bg-gray"><%= t(:todo) %></div>

  <% open_todos = issue.todo_items.where(:workflow_state => :open) %>

  <%= render open_todos, :manage => false %>

  <% todos_done = issue.todo_items.where(:workflow_state => :done) %>
  <% if todos_done.any? %>
    <div id="todo_done" style="<%= %(border-top: 1px solid #DDD;) if open_todos.any? %>">
      <%= render todos_done, :manage => false %>
    </div>
  <% end %>
</div>
<% end %>

app/views/issues/assign_to.js.erb
$("#issue_assignment").html("<%= escape_javascript render('shared/issue_assignment', :issue => @issue) %>")
location.reload();

app/views/issues/change_state.js.erb
$("#issue_workflow_box").html("<%= escape_javascript(render('shared/issue_workflow', :issue => @issue)) %>")
<% if @issue.closed? or @issue.reopened? %>
  location.reload()
<% end %>

app/views/issues/edit.html.erb
<article class="module width_full">
	<header><h3><%= t('issue.edit') %></h3></header>
	<%= render 'form' %>
</article>   

<div class="spacer"></div>

app/views/issues/index.html.erb
<% content_for :sidebar do %>
  <div class="b-box">
    <div class="bar bg-gray"><%= t(:issue_label) %></div>
    <% ['task', 'bug', 'suggestion'].each do |label| %>
      <div class="row bg_highlight quiet" <%= 'filtered' if label == @label %> clickable="<%= project_issues_path(@project) %>/label/<%= label %>"><%= t("issue.label.#{label}") %></div>
    <% end %>
  </div>

  <div class="b-box" title="<%= t(:click_to_filter_issues) %>">
    <div class="bar bg-gray"><%= t(:issue_state) %></div>
    <% Issue.all_states.each do |state_sym| %>
      <div class="row bg_highlight" <%= "filtered" if state_sym.to_s == @issue_state %> clickable="<%= project_issues_path(@project) %>/filter/<%= state_sym.to_s %>">
        <span class="quiet span-2"><%= @project.issues.send("only_#{state_sym.to_s}").count %></span>
        <span class="state state-<%= state_sym.to_s %>"><%= Issue.state_name(state_sym) %></span>
      </div>
    <% end %>
  </div>
<% end %>

<span>
  <%= link_to t(:new_task), new_project_issue_path(@project) + '/task' %>
  &nbsp;&nbsp;
  <%= link_to t(:new_bug), new_project_issue_path(@project) + '/bug' %>
  &nbsp;&nbsp;
  <%= link_to t(:new_suggestion), new_project_issue_path(@project) + '/suggestion' %>
</span>
<%= render 'shared/line_spacer' %>
<%= render_with_spacer 'issue', @issues.order('created_at DESC') %>

app/views/issues/new.html.erb
<article class="module width_full">
	<header><h3><%= icon(@label) + t("new_#{@label}") %></h3></header>
	<%= render 'form' %>
</article>

<div class="spacer"></div>   
<!-- end of post new article -->

app/views/issues/search.html.erb
<article class="module width_full">
  <header>
    <h3 class="tabs_involved"><%= t('search.results') %></h3>
  </header>
  <div class="module_content">
    <% if @result.any? %>
    <%= render :partial => 'issues/issue', :collection => @result %>
    <% else %>
      <div class="row"><%= t('search.no_issue_found') %></div>
    <% end %>
  </div>
</article>

app/views/issues/show.html.erb
<div class="module width_3_quarter">
  <header><h3><%= icon(@issue.label) + @issue.title %></h3></header>

  <div class="module_content">
    <div class="tip">
      By <%= link_to @issue.user.name, @issue.user, :class => "quiet" %>
      &nbsp;&middot;&nbsp;
      <span class="date"><%= time_ago_in_words(@issue.created_at) + t(:ago) %></span>
      <% if can? :manage, @issue %>
        &nbsp;&middot;&nbsp;
        <%= link_to t(:edit), edit_issue_path(@issue), :class => :action %>
        &nbsp;&middot;&nbsp;
        <%= link_to t(:delete), @issue, :method => :delete, :class => :action, :confirm => t(:delete_confirm) %>
      <% end %>
    </div>

    <%=raw parse_markdown @issue.content %>

    <% if can? :manage_todo, @issue %>
      <div id="todo_list_box">
        <%= render 'manage_todo_list', :issue => @issue, :todo_item => @todo_item %>
      </div>
    <% else %>
      <%= render 'view_todo_list', :issue => @issue %>
    <% end %>
  </div>
</div>

<article class="module width_quarter" id="issue_workflow_box">
    <%= render 'shared/issue_workflow', :issue => @issue %>
</article>

<article class="module width_quarter" id="issue_assignment">
  <%= render 'shared/issue_assignment', :issue => @issue %>
</article>

<% if can? :manage_todo, @issue %>
  <% content_for :on_ready_hook do %>
      $("input[type=checkbox]").live('change', function() {
          var item_id = $(this).attr('data-id');
          var input = $(this);
          if (input.is(":checked")) {
            // from 'unchecked' to 'checked', mark item as done
            // TODO: The event is hardcoded! should be automatically set from todo_item state
            $.post('/todo_items/' + item_id + '/change_state', {event: "finish"}, function() {
              input.next().removeClass('todo_new').addClass('todo_done');
              var target = $("#todo_" + item_id);
              target.hide();
              $("#todo_done").append(target);
              target.slideDown();
            });
          } else {
            // uncheck this item, mark as 'new'
            $.post('/todo_items/' + item_id + '/change_state', {event: "undo"}, function() {
              input.next().removeClass('todo_done').addClass('todo_new');
              var target = $("#todo_" + item_id);
              target.hide();
              $("#add_todo_form").before(target);
              target.slideDown();
            });
          }
      });

      $.make_sortable('todo_list_box', '/todo_items/sort');
  <% end %>
<% end %>

<div class="module width_3_quarter">
  <header><h3><%= t('issue.discussions') %></h3></header>
  <div class="module_content">
    <!-- @Comments -->
    <a name="comments" href=""></a>

    <% unless @issue.closed? and @issue.comments.empty? %>
      <div id="issue_comments">
        <%= render @issue.comments %>
      </div>
    <% end %>

    <div class="<%= "hide" if @issue.closed? %>" id="add_comment_form">
      <%= form_for [@issue, @comment], :remote => true do |f| %>
        <fieldset>
          <%= f.text_area :content, :style => "height: 10em" %><br />
        </fieldset>
        <%= f.submit t('issue.create_comment') %>
      <% end %>
    </div>
  </div>
</div>

<% if @issue.milestone %>
  <article class="module width_quarter">
    <header><h3><%= t(:milestone) %></h3></header>
    <div class="module_content">
      <%= link_to @issue.milestone.name, project_path(@issue.project) + '#milestones' %>
    </div>
  </article>
<% end %>

<div class="spacer clear"></div>