config/routes.rb
InternalProjMgmt::Application.routes.draw do
  get 'register' => 'users#new'
  get '/search/:keyword' => 'issues#search'
  get 'rebuild_index' => 'issues#rebuild_index'
  get '/stats' => "pages#stats"

  post '/user_sessions' => "user_sessions#create"
  get 'logout' => "user_sessions#destroy"

  post '/assigned_issues/sort' => 'issue_assignments#sort'
  
  resources :activities, :only => :create
  resources :users, :comments
  resources :projects do
    resources :issues do
      collection do
        get 'new/:label' => 'issues#new'
        get 'filter/:state', :action => 'index'
        get 'label/:label', :action => 'view_by_label'
      end
    end
    resources :milestones, :documents
  end

  get "milestones/new"
  post "milestones/create"

  resources :issues do
    resources :comments
    resources :todo_items

    member do
      post 'change_state'
      post 'assign_to'
      post 'planning'
    end

    collection do
      get 'autocomplete'
    end
  end

  resources :todo_items do
    member do
      post :change_state
    end

    collection do
      post :sort
    end
  end

  resource :account
  resources :images, :only => [:new, :create, :destroy]

  namespace 'sudo' do
    resources :users
  end

  root :to => "pages#index"

end

app/views/shared/_all_users.html.erb
  <div class="bar bg-blue"><%= t(:all_users) %></div>
  <%= render 'user', User.all %>

app/views/shared/_drag_handle.html.erb
<span class="drag_handle"><%= image_tag 'cursor_drag_arrow.png', :width => 16, :height => 16, :align => :absmiddle %></span>

app/views/shared/_editor.html.erb
<% content_for :head_hook do %>
  <%= stylesheet_link_tag :gollum %>
  <!--[if IE 7]>
    <%= stylesheet_link_tag "gollum_ie7" %>
  <![endif]-->
  <%= javascript_include_tag :gollum %>
<% end %>

<% content_for :on_ready_hook do %>
  $.GollumEditor();
<% end %>

<div id="gollum-editor">
  <input type="hidden" name="page" id="gollum-editor-page-title" value="Home">
  <div id="gollum-editor-function-bar">
    <div id="gollum-editor-function-buttons">
      <a href="#" id="function-bold" class="function-button">
        <span>Bold</span></a>
      <a href="#" id="function-italic" class="function-button">
        <span>Italic</span></a>
      <a href="#" id="function-code" class="function-button">
        <span>Code</span></a>
      <span class="function-divider">&nbsp;</span>
      <a href="#" id="function-ul" class="function-button">
        <span>Unordered List</span></a>
      <a href="#" id="function-ol" class="function-button">
        <span>Ordered List</span></a>
      <a href="#" id="function-blockquote" class="function-button">
        <span>Blockquote</span></a>

      <a href="#" id="function-hr" class="function-button">
        <span>Horizontal Rule</span></a>
      <span class="function-divider">&nbsp;</span>
      <a href="#" id="function-h1" class="function-button">
        <span>h1</span></a>
      <a href="#" id="function-h2" class="function-button">
        <span>h2</span></a>
      <a href="#" id="function-h3" class="function-button">
        <span>h3</span></a>
      <span class="function-divider">&nbsp;</span>
      <a href="#" id="function-link" class="function-button">
        <span>Link</span></a>
      <a href="#" id="function-image" class="function-button">
        <span>Image</span></a>
      <span class="function-divider">&nbsp;</span>
      <a href="#" id="function-help" class="function-button">
        <span>Help</span></a>
    </div>
  </div>
  <div id="gollum-editor-help" class="jaws">
    <ul id="gollum-editor-help-parent">
      <li><a href="javascript:void(0);" class="selected">Help 1</a></li>
      <li><a href="javascript:void(0);">Help 1</a></li>
      <li><a href="javascript:void(0);">Help 1</a></li>
    </ul>
    <ul id="gollum-editor-help-list">
      <li><a href="javascript:void(0);">Help 2</a></li>
      <li><a href="javascript:void(0);">Help 3</a></li>
      <li><a href="javascript:void(0);">Help 4</a></li>
      <li><a href="javascript:void(0);">Help 5</a></li>
      <li><a href="javascript:void(0);">Help 6</a></li>
      <li><a href="javascript:void(0);">Help 7</a></li>
      <li><a href="javascript:void(0);">Help 8</a></li>
    </ul>
    <div id="gollum-editor-help-wrapper">
      <div id="gollum-editor-help-content">
      <p>
      </p>
      </div>
    </div>
  </div>
  <textarea id="gollum-editor-body" data-markup-lang="markdown" name="<%= name %>"><%= content %></textarea>
</div>

app/views/shared/_error_messages.html.erb
<% if obj.errors.any? %>
  	<h4 class="alert_error">
	   <% if obj.errors.count > 1 %>
	     <%= t('activerecord.errors.template.header.other', :count => obj.errors.count, :model => obj.class.to_s.downcase) %>
	   <% else %>
	     <%= t('activerecord.errors.template.header.one', :model => obj.class.to_s.downcase) %>
	   <% end %>
	   <ul>
	    <% obj.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>  
	    <% end %>
	   </ul>
	</h4>
<% end %>

app/views/shared/_ga.html.erb
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-12942904-5']);
  _gaq.push(['_trackPageview']);

  (function() {
   var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
   ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
   var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
   })();
</script>

app/views/shared/_issue_assignment.html.erb
<header>
	<h3>
	  <% if @issue.assigned_user %>
	    <strong><%= t('issue.assignment.assigned_to') %></strong>
	    <% if @issue.assigned_user == current_user %>
	      <%= link_to t(:me), current_user %>
	    <% else %>
	      <%= link_to @issue.assigned_user.name, @issue.assigned_user %>
	    <% end %>
	  <% else %>
	    <span class="quiet">{ <%= t('issue.assignment.not_assigned') %> }</span>
	  <% end %>
	</h3>
</header>

<div class="module_content">
  <% if can? :assign, @issue %>
  <%= form_for :issue_assignment, :url => assign_to_issue_path(@issue), :remote => true do |f| %>
    <%= t('issue.assignment.assign_to') %>
    <%= select_tag :user_id, options_for_select(
      User.all.collect do |user| 
      (user == current_user) ? [t(:me), user.id] : [user.name, user.id] 
      end) %>
    <%= f.submit t(:save) %>
  <% end %>
<% else %>
  <span class="quiet"><%= t('permission.cannot_assign_issue') %></span>
<% end %>
</div>

app/views/shared/_issue_workflow.html.erb
<header><h3><%= t('issue.workflow.current_state') %> <span class="state state-<%= issue.current_state.name.to_s %>"><%= issue.current_state_name %></span></h3></header>
<% keys = issue.current_state.events.keys %>
<div class="module_content">
  <% if @issue.assigned_user.nil? %>
    <span class="quiet"><%= t(:assign_to_an_user_first) %></span>
  <% elsif can? :change_state, issue %>
    <% if keys.length == 1 %>
      <%= as_button(link_to Issue.event_name(keys.first), change_state_issue_path(issue, :event => keys.first.to_s), :remote => true, :method => :post) %>
    <% else %>
      <%= form_for :issue, :url => change_state_issue_path(issue), :remote => true do |f| %>
        <%= select_tag :event, options_for_select(keys.collect { |key| [Issue.event_name(key), key.to_s] }) %>
        <%= f.submit t(:update) %>
      <% end %>
    <% end %>
  <% else %>
    <span class="quiet"><%= t('permission.cannot_update_workflow') %></span>
  <% end %>
</div>

app/views/shared/_no_items.html.erb
<div class="row quiet"><%= t(:no_items_right_now) %></div>

app/views/shared/_role.html.erb
<span class="state bg-999"><%= role %></span>