config/routes.rb
InternalProjMgmt::Application.routes.draw do
  get 'register' => 'users#new'
  get '/search/:keyword' => 'issues#search'
  get 'rebuild_index' => 'issues#rebuild_index'
  get '/stats' => "pages#stats"

  post '/user_sessions' => "user_sessions#create"
  get 'logout' => "user_sessions#destroy"

  post '/assigned_issues/sort' => 'issue_assignments#sort'
  
  resources :activities, :only => :create
  resources :users, :comments
  resources :projects do
    resources :issues do
      collection do
        get 'new/:label' => 'issues#new'
        get 'filter/:state', :action => 'index'
        get 'label/:label', :action => 'view_by_label'
      end
    end
    resources :milestones, :documents
  end

  get "milestones/new"
  post "milestones/create"

  resources :issues do
    resources :comments
    resources :todo_items

    member do
      post 'change_state'
      post 'assign_to'
      post 'planning'
    end

    collection do
      get 'autocomplete'
    end
  end

  resources :todo_items do
    member do
      post :change_state
    end

    collection do
      post :sort
    end
  end

  resource :account
  resources :images, :only => [:new, :create, :destroy]

  namespace 'sudo' do
    resources :users
  end

  root :to => "pages#index"

end

app/models/document.rb
# == Schema Information
# Schema version: 20110604071850
#
# Table name: documents
#
#  id         :integer         not null, primary key
#  project_id :integer
#  user_id    :integer
#  title      :string(255)
#  content    :text
#  created_at :datetime
#  updated_at :datetime
#

class Document < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  
  validates :title, :content, :project_id, :user_id, :presence => true
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_filter :must_login_first
  before_filter :find_project
  before_filter :find_document, :except => [:new, :create]
  authorize_resource
  
  def new
    @project = Project.find(params[:project_id])
    @document = @project.documents.new
    
    breadcrumbs.add @project.name, project_path(@project)
    breadcrumbs.add t(:new_document)
  end
  
  def create
    @project = Project.find(params[:project_id])
    @document = @project.documents.build(params[:document])
    @document.user = current_user
    if @document.save
      Activity.create!(
        :user_id => current_user.id,
        :project_id => params[:project_id],
        :event_name => 'create_document',
        :target_id => @document.id,
        :data => {:project_name => @project.name, :document_title => @document.title}
      )
      redirect_to [@project, @document]
    else
      render :new
    end
  end
  
  def show
    breadcrumbs.add @project.name, project_path(@project)
    breadcrumbs.add "#doc-#{@document.id}", project_document_path(@project, @document)
  end
  
  def edit
    breadcrumbs.add @project.name, project_path(@project)
    breadcrumbs.add "#doc-#{@document.id}", project_document_path(@project, @document)
    breadcrumbs.add t(:edit)
  end
  
  def update
    if @document.update_attributes(params[:document])
      redirect_to [@project, @document]
    else
      render :edit
    end
  end
  
  def destroy
    if @document.destroy
      redirect_to @project
    else
      flash[:error] = t(:destroy_failed)
      redirect_to root_path
    end
  end
  
  private
    def find_project
      @project = Project.find(params[:project_id])      
    end
    
    def find_document
      @document = @project.documents.find(params[:id])
    end
end

app/views/documents/_document.html.erb
<div class="issue_item ui-corner-all">
  <%= link_to document.title, project_document_path(project, document) %>
  <span class="date"><%= time_ago_in_words(document.created_at) + t(:ago) %></span>
</div>

app/views/documents/_form.html.erb
<%= form_for [@project, @document] do |f| %>
  <%= render 'shared/error_messages', :obj => f.object %>
  <fieldset>
    <%= f.label :title, t(:title) %>
    <%= f.text_field :title %>
  </fieldset>
  
  <fieldset>
    <%= f.label :content, t(:content) %>
    <%= render :partial => 'shared/editor',
      :locals => {:name => 'document[content]', :content => @document.content} %>
  </fieldset>
  <%= f.submit t(:save), :class => :alt_btn %>
<% end %>

app/views/documents/edit.html.erb
<article class="module width_full">
  <header>
    <h3><%= icon 'doc' %><%= t(:edit_document) %></h3>
  </header>
  <div class="module_content">
    <%= render 'form' %>
  </div>
</article>

app/views/documents/new.html.erb
<article class="module width_full">
  <header>
    <h3><%= icon 'doc' %><%= t(:new_document) %></h3>
  </header>
  <div class="module_content">
    <%= render 'form' %>
  </div>
</article>

app/views/documents/show.html.erb
<article class="module width_full">
  <header>
    <h3 class="tabs_involved">
      <%= icon 'doc' %>
      <%= @document.title %>
    </h3>
  </header>
  <div class="module_content">
    <%=raw parse_markdown(@document.content) %>
  </div>
  <% if can? :manage, @document %>
  <footer>
    <ul class="actions">
      <li><%= link_to t(:edit), edit_project_document_path(@project, @document), :class => :btn %></li>
      <li><%= link_to t(:delete), project_document_path(@project, @document),
        :method => :delete, :confirm => t(:delete_confirm), :class => :btn %></li>
    </ul>
  </footer>
  <% end %>
</article>