config/routes.rb
InternalProjMgmt::Application.routes.draw do
  get 'register' => 'users#new'
  get '/search/:keyword' => 'issues#search'
  get 'rebuild_index' => 'issues#rebuild_index'
  get '/stats' => "pages#stats"

  post '/user_sessions' => "user_sessions#create"
  get 'logout' => "user_sessions#destroy"

  post '/assigned_issues/sort' => 'issue_assignments#sort'
  
  resources :activities, :only => :create
  resources :users, :comments
  resources :projects do
    resources :issues do
      collection do
        get 'new/:label' => 'issues#new'
        get 'filter/:state', :action => 'index'
        get 'label/:label', :action => 'view_by_label'
      end
    end
    resources :milestones, :documents
  end

  get "milestones/new"
  post "milestones/create"

  resources :issues do
    resources :comments
    resources :todo_items

    member do
      post 'change_state'
      post 'assign_to'
      post 'planning'
    end

    collection do
      get 'autocomplete'
    end
  end

  resources :todo_items do
    member do
      post :change_state
    end

    collection do
      post :sort
    end
  end

  resource :account
  resources :images, :only => [:new, :create, :destroy]

  namespace 'sudo' do
    resources :users
  end

  root :to => "pages#index"

end

app/models/project.rb
# == Schema Information
# Schema version: 20110415124331
#
# Table name: projects
#
#  id         :integer         not null, primary key
#  user_id    :integer
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Project < ActiveRecord::Base
  belongs_to :user

  has_many :issues, :dependent => :destroy
  has_many :milestones, :dependent => :destroy
  has_many :activities, :dependent => :destroy
  has_many :documents, :dependent => :destroy

  validates :name, :user_id, :presence => true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :must_login_first
  before_filter :root_required, :only => :destroy

  def index
    @projects = Project.all
    @title = t(:all_projects)

    breadcrumbs.add t(:all_projects), projects_path
  end

  def show
    @project = Project.find(params[:id])
    @title = @project.name
    breadcrumbs.add @project.name, project_path(@project)
  end

  def new
    @project = current_user.projects.new
    @title = t(:new_project)
  end

  def create
    @project = current_user.projects.new(params[:project])
    if @project.save
      Activity.create!(
        :user_id => current_user.id,
        :event_name => 'create_project',
        :project_id => @project.id,
        :data => {:name => @project.name}
      )
      redirect_to @project
    else
      render :new
    end
  end

  def edit
    @title = t(:edit_project)
  end

  def update
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      redirect_to root_path
    else
      render :text => 'ERROR', :status => 500
    end
  end

end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>

  <%= render 'shared/error_messages', :obj => @project %>
<fieldset>
    <%= f.label :name, t(:project_name) %>
    <%= f.text_field :name %>

</fieldset>  <%= f.submit t(:create_project) %>

<% end %>

app/views/projects/_project.html.erb
	<article class="module width_full">
	<header><h3><%= link_to project.name, project %></h3></header>
		<div class="module_content">
			<%= render project.issues.order('created_at DESC').limit(5) %>
		</div>
</article>

app/views/projects/_simple_style.html.erb
<%= image_tag 'folder.png', :align => :absmiddle, :width => 16, :height => 16 %>&nbsp;<%= link_to project.name, project %>

app/views/projects/index.html.erb
<%= render @projects %>

app/views/projects/new.html.erb
<article class="module width_full">

	<header><h3><%= t(:create_project) %></h3></header>

		<div class="module_content">
			<%= render 'form' %>		
		</div>

</article>
<!-- end of messages article -->

app/views/projects/show.html.erb
<article class="module width_full">
  <header>
    <h3 class="tabs_involved">
      <%= icon 'milestone' %>
      <%= t('project.milestones') %>
    </h3>
  </header>
  <a name="milestones" href=""></a>
  <div class="module_content">
    <%= render @project.milestones, :project => @project %>
  </div>
  <% if can? :manage_milestone, @project %>
    <footer>
      <ul class="actions">
        <li><%= link_to new_project_milestone_path(@project),
          :class => :btn do icon('add') + t(:new_milestone) end %>
        </li>
      </ul>
    </footer>
  <% end %>
</article>

<article class="module width_full">
  <header>
    <h3 class="tabs_involved">
      <%= icon 'task' %>
      <%= t('project.tasks') %>
    </h3>
  </header>
  <a name="tasks" href=""></a>
  <div class="module_content">
    <%= render @project.issues.where(['label = ?', 'task']).limit(10) %>
  </div>
  <footer>
    <ul class="actions">
      <li><%= link_to new_project_issue_path(@project) + '/task', :class => :btn do icon('add') + t(:new_task) end %></li>
    </ul>
  </footer>
</article>

<article class="module width_full">
  <header>
    <h3 class="tabs_involved">
      <%= icon 'bug' %>
      <%= t('project.bugs') %>
    </h3>
  </header>
  <a name="bugs" href=""></a>
  <div class="module_content">
    <%= render @project.issues.where(['label = ?', 'bug']).limit(10) %>
  </div>
  <footer>
    <ul class="actions">
      <li><%= link_to new_project_issue_path(@project) + '/bug', :class => :btn do icon('add') + t(:new_bug) end %></li>
    </ul>
  </footer>
</article>

<article class="module width_full">
  <header>
    <h3 class="tabs_involved">
      <%= icon 'idea' %>
      <%= t('project.ideas') %>
    </h3>
  </header>
  <a name="ideas" href=""></a>
  <div class="module_content">
    <%= render @project.issues.where(['label = ?', 'idea']).limit(10) %>
  </div>
  <footer>
    <ul class="actions">
      <li><%= link_to new_project_issue_path(@project) + '/idea', :class => :btn do icon('add') + t(:new_idea) end %></li>
    </ul>
  </footer>
</article>

<article class="module width_full">
  <header>
    <h3 class="tabs_involved">
      <%= icon 'doc' %>
      <%= t('project.docs') %>
    </h3>
  </header>
  <a name="docs" href=""></a>
  <div class="module_content">
    <%= render @project.documents, :project => @project %>
  </div>
  <footer>
    <ul class="actions">
      <li><%= link_to new_project_document_path(@project), :class => :btn do icon('add') + t(:new_document) end %></li>
  </footer>
</article>

<% if current_user.root? %>
  <h4 class="alert_error"><%= link_to t(:delete), @project, :method => :delete, :confirm => t(:delete_confirm) %></h4>
<% end %>

<div class="clear"></div>